[manifest]
version = "1.0.0"
dump_lua = true
priority = 2

## Chameleon tooltip
[[patches]]
[patches.pattern]
target = 'engine/moveable.lua'
pattern = '''Node.init(self, args)'''
position = 'after'
match_indent = true
payload = '''self.T_ref = copy_table(self.T)'''
