[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
if SMODS.has_enhancement(scoring_hand[i], 'm_glass') and not scoring_hand[i].debuff and pseudorandom('glass') < G.GAME.probabilities.normal/(scoring_hand[i].ability.name == 'Glass Card' and scoring_hand[i].ability.extra or G.P_CENTERS.m_glass.config.extra) then
    destroyed = true
end
'''
position = 'at'
match_indent = true
payload = '''
print('Debug: CeCi_patch is working.')
if SMODS.has_enhancement(scoring_hand[i], 'm_glass') and not scoring_hand[i].debuff then
    local glass_odds = G.P_CENTERS.m_glass.config.extra
    if scoring_hand[i].ability.name == 'Glass Card' then
        glass_odds = scoring_hand[i].ability.extra or glass_odds
    end
    if pseudorandom('glass') < G.GAME.probabilities.normal/glass_odds then
        destroyed = true
        for j = 1, #G.jokers.cards do
            local glass_state = G.jokers.cards[j]:calculate_joker({about_to_shatter = true, card = self})
            print('durable: '..glass_state.very_durable)
            if glass_state.very_durable then
                destroyed = false
            end
        end
    end
end
'''
