[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.cost > 0 then"
position = "before"
match_indent = true
payload = '''
for i = 1, #G.jokers.cards do
    G.jokers.cards[i]:calculate_joker({buying_booster_pack = true, card = self})
end'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "G.GAME.used_vouchers[self.config.center_key] = true"
position = "after"
match_indent = true
payload = '''
for i = 1, #G.jokers.cards do
    G.jokers.cards[i]:calculate_joker({buying_voucher = true, card = self})
end'''
